vich_uploader:
    db_driver: orm
    mappings:
        coach:
            uri_prefix: /uploads/coach-photos
            upload_destination: '%kernel.project_dir%/public/uploads/coach-photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
